orbs:
  doctl: digitalocean/cli@0.1.1
version: 2.1
workflows:
  install_and_configure_cli:
    jobs:
      - doctl/install_and_initialize_cli:
          context: mahitmvpn
          executor: doctl/default
