version: 2.1

jobs:   
  build_amd64: 
    docker: 
    - image: cimg/rust:1.71
    resource_class: large
    steps: 
      - checkout 
      - restore_cache:
          keys:
            - v2-cargo-mahitm-vpn-server-cache-{{ arch }} # {{ checksum "Cargo.lock" }}
      - run: 
          name: Install Debian Build Tool
          command: |
            cargo install cargo-deb 
      - run: 
          name: Build 
          command: | 
            cargo-deb
      - persist_to_workspace:
          root: ./target
          paths:
            - debian/*.deb
      - save_cache:
          paths:
            - /home/circleci/.cargo/registry
            - /home/circleci/.cargo/bin
            - /home/circleci/.cargo/.crates.toml
            -  /home/circleci/.cargo/.crates2.json
            - target
          key: v2-cargo-mahitm-vpn-server-cache-{{ arch }} # {{ checksum "Cargo.lock" }}
  build_arm64: 
    docker: 
      - image: cimg/rust:1.71
    resource_class: arm.large
    steps: 
      - checkout 
      - restore_cache:
          keys:
            - v2-cargo-mahitm-vpn-server-cache-{{ arch }} # {{ checksum "Cargo.lock" }}
      - run: 
          name: Install Debian Build Tool
          command: |
            cargo install cargo-deb 
      - run: 
          name: Build 
          command: | 
            cargo-deb
      - persist_to_workspace:
          root: ./target
          paths:
            - debian
      - save_cache:
          paths:
            - /home/circleci/.cargo/registry
            - /home/circleci/.cargo/bin
            - /home/circleci/.cargo/.crates.toml
            -  /home/circleci/.cargo/.crates2.json
            - target
          key: v2-cargo-mahitm-vpn-server-cache-{{ arch }} # {{ checksum "Cargo.lock" }}
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./target
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./target/debian/
workflows:
  build_and_release: 
    jobs: 
      - build_arm64:
          filters:
            tags:
              only:
                - /v.*/
            branches:
              ignore: /.*/
      - build_amd64:
          filters:
            tags:
              only:
                - /v.*/
            branches:
              ignore: /.*/
      - publish-github-release:
          filters:
            tags:
              only:
                - /v.*/
            branches:
              ignore: /.*/
          context: gh_secrets
          requires: 
            - build_arm64 
            - build_amd64
