version: 2.1

commands: 
  doctl_install:
    description: Install the doctl, if not available
    steps:
      - run: 
          command: |
            cat /etc/os-release
      - run: 
          command: |
            sudo apt update
            sudo apt install snapd
            sudo snap install doctl
            sudo snap connect doctl:dot-docker
      - run: 
          command: |
            doctl version     
  doctl_initialize:
    description: Initilize the digitalocean CLI
    parameters:
      digitalocean-access-token:
        default: DIGITALOCEAN_ACCESS_TOKEN
        description: |
          Name of environment variable storing the digitalocean v2 api access token
        type: env_var_name
    steps:
      - run:
          command: |
            sudo doctl auth init -t $<<parameters.digitalocean-access-token>>
          name: Initialize doctl

jobs:           
  build: 
    parameters:
      digitalocean-access-token:
        default: DIGITALOCEAN_ACCESS_TOKEN
        description: |
          Name of environment variable storing the digitalocean v2 api access token
        type: env_var_name
    docker: 
      - image: cimg/rust:1.70.0
        environment: 
          WG_HOST=$WG_HOST
          WG_PORT=$WG_PORT
          WG_TUNNEL_ID=$WG_TUNNEL_ID
          FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
          FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID
          FIREBASE_CLIENT_SECRET=$FIREBASE_CLIENT_SECRET
          FIREBASE_REFRESH_TOKEN=$FIREBASE_REFRESH_TOKEN
    steps: 
      - doctl_install
      - doctl_initialize
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Docker Compose Build
          command: |
            docker compose build
      - run: 
          name: Login to DigitalOcean Registry
          command: |
            doctl registry login
      - run: 
          name: Push to DigitalOcean Registry
          command: |  
            docker image tag project-mahitm-vpn:latest "registry.digitalocean.com/mahitm/vpn"
            docker push "registry.digitalocean.com/mahitm/vpn"
workflows:
  build_and_upload: 
    jobs: 
      - build: 
          context: mahitmvpn
