version: 2.1

commands: 
  doctl_install:
    description: Install the doctl, if not available
    steps:
      - run: 
          command: |
            cat /etc/os-release
      - run: 
          command: |
            apk update
            apk upgrade --available
            apk --no-cache add doctl
      - run: 
          command: |
            doctl version     
  doctl_initialize:
    description: Initilize the digitalocean CLI
    parameters:
      digitalocean-access-token:
        default: DIGITALOCEAN_ACCESS_TOKEN
        description: |
          Name of environment variable storing the digitalocean v2 api access token
        type: env_var_name
    steps:
      - run:
          command: |
            doctl auth init -t $<<parameters.digitalocean-access-token>>
          name: Initialize doctl

jobs:           
  build: 
    parameters:
      digitalocean-access-token:
        default: DIGITALOCEAN_ACCESS_TOKEN
        description: |
          Name of environment variable storing the digitalocean v2 api access token
        type: env_var_name
    docker: 
      - image: docker:24.0.2-git
        environment: 
          WG_HOST=$WG_HOST
          WG_PORT=$WG_PORT
          WG_TUNNEL_ID=$WG_TUNNEL_ID
          FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
          FIREBASE_CLIENT_ID=$FIREBASE_CLIENT_ID
          FIREBASE_CLIENT_SECRET=$FIREBASE_CLIENT_SECRET
          FIREBASE_REFRESH_TOKEN=$FIREBASE_REFRESH_TOKEN
    steps: 
      - doctl_install
      - doctl_initialize
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Docker Compose Build
          command: |
            docker compose -f docker-compose.yml -f production.yml build
      - run: 
          name: Login to DigitalOcean Registry
          command: |
            doctl registry login
      - run: 
          name: Push to DigitalOcean Registry
          command: |  
            docker compose push

workflows:
  build_and_upload: 
    jobs: 
      - build: 
          context: mahitmvpn