name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Install Debian Build Tool 
      run: cargo install cargo-deb
    - name: Build
      run: cargo-deb 
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.deb"
