name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Debian Build Tool 
      run: cargo install cargo-deb
    - name: Build
      run: cargo-deb 
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "target/debian/*.deb"
